/**
 * Self-signed certificates for a cluster, generated by the deploy tool.
 *
 * This was a `Custom::SelfSignedCertificate*` Lambda whose Delete force-destroyed the two secrets
 * a live load balancer was serving. Generating here instead means the destructive path does not
 * exist: nothing in this module deletes a secret or an ACM certificate.
 *
 * The secret names, descriptions, tags and subject fields are the ones the Python handler used, so
 * a cluster that already has a pair keeps it. Only the tag `idea:SecretName` is searched, because
 * `secretsmanager:GetSecretValue` takes no condition key on the name and the tag is what the
 * policies are written against.
 *
 * One deliberate difference from the handler: a pair with exactly one half present is an error
 * rather than a regeneration. The handler regenerated both, which replaced a private key a
 * listener was serving.
 */

import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { GeneralException } from '../config/cluster-config.ts';

/** The tag the secrets are found by, and the IAM policies are written against. */
export const SECRET_NAME_TAG = 'idea:SecretName';

/** Ten years, as the handler's `not_valid_after` computed it. */
export const CERTIFICATE_VALIDITY_DAYS = 3650;

export interface CertificateRequest {
  /** `<certificateName>-certificate` and `<certificateName>-private-key` are the secret names. */
  certificateName: string;
  domainName: string;
  /** The common tags every created resource carries, without `idea:SecretName`. */
  tags: Record<string, string>;
  kmsKeyId?: string;
  /** True for the load-balancer certificates, which a listener can only name through ACM. */
  importToAcm: boolean;
}

export interface CertificateResult {
  certificateSecretArn: string;
  privateKeySecretArn: string;
  acmCertificateArn?: string;
}

export interface Tag {
  Key: string;
  Value: string;
}

export interface SecretSummary {
  Name?: string;
  ARN?: string;
}

export interface CreateSecretInput {
  Name: string;
  Description: string;
  SecretString: string;
  Tags: Tag[];
  KmsKeyId?: string;
}

/** The two Secrets Manager calls this module makes, as a functional interface so tests need no credentials. */
export interface SecretsApi {
  listSecretsByTagValue(tagKey: string, tagValues: string[]): Promise<SecretSummary[]>;
  /** Returns the ARN of the created secret. */
  createSecret(input: CreateSecretInput): Promise<string>;
}

export interface AcmCertificateSummary {
  DomainName?: string;
  CertificateArn?: string;
}

export interface AcmApi {
  listIssuedCertificates(): Promise<AcmCertificateSummary[]>;
  /** Returns the ARN of the imported certificate. */
  importCertificate(input: { Certificate: string; PrivateKey: string; Tags: Tag[] }): Promise<string>;
}

export interface OpensslResult {
  status: number | null;
  stderr: string;
  /** True when the binary itself was not found, which gets its own message. */
  missing?: boolean;
}

/** Runs `openssl` with these arguments in this working directory. */
export type OpensslRunner = (args: readonly string[], cwd: string) => OpensslResult;

export interface CertificateDeps {
  secrets: SecretsApi;
  acm: AcmApi;
  openssl: OpensslRunner;
}

function commonTags(tags: Record<string, string>): Tag[] {
  return Object.entries(tags).map(([Key, Value]) => ({ Key, Value }));
}

/** The arguments the certificate is generated with, so the test and the runner cannot disagree. */
export function opensslArgs(
  request: Pick<CertificateRequest, 'certificateName' | 'domainName'>,
  certificateFile: string,
  privateKeyFile: string,
): string[] {
  return [
    'req',
    '-x509',
    '-newkey',
    'rsa:2048',
    '-nodes',
    '-days',
    String(CERTIFICATE_VALIDITY_DAYS),
    '-subj',
    `/C=US/ST=California/L=Sunnyvale/O=${request.certificateName}/CN=${request.domainName}`,
    '-addext',
    `subjectAltName=DNS:${request.domainName}`,
    '-addext',
    'basicConstraints=critical,CA:FALSE',
    '-keyout',
    privateKeyFile,
    '-out',
    certificateFile,
  ];
}

/** The PEM pair, in a temporary directory that is removed before this returns. */
function generate(request: CertificateRequest, openssl: OpensslRunner): { certificate: string; privateKey: string } {
  const directory = mkdtempSync(join(tmpdir(), 'idea-self-signed-'));
  try {
    const certificateFile = join(directory, 'certificate.pem');
    const privateKeyFile = join(directory, 'private-key.pem');
    const result = openssl(opensslArgs(request, certificateFile, privateKeyFile), directory);
    if (result.missing === true) {
      throw new GeneralException(
        `openssl was not found on PATH, and ${request.certificateName} needs it to generate a self-signed certificate. ` +
          'Install openssl, or supply your own certificate and set the module\'s certificates.provided setting.',
      );
    }
    if (result.status !== 0) {
      throw new GeneralException(
        `openssl exited ${String(result.status)} generating ${request.certificateName}: ${result.stderr.trim()}`,
      );
    }
    return {
      certificate: readFileSync(certificateFile, 'utf-8'),
      privateKey: readFileSync(privateKeyFile, 'utf-8'),
    };
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

/**
 * The certificate pair for one name: adopted when both secrets are already there, generated when
 * neither is. `importToAcm` additionally resolves an ISSUED ACM certificate for the domain,
 * importing the generated pair when there is none.
 */
export async function ensureSelfSignedCertificate(
  request: CertificateRequest,
  deps: CertificateDeps,
): Promise<CertificateResult> {
  const certificateSecretName = `${request.certificateName}-certificate`;
  const privateKeySecretName = `${request.certificateName}-private-key`;

  const existing = await deps.secrets.listSecretsByTagValue(SECRET_NAME_TAG, [
    certificateSecretName,
    privateKeySecretName,
  ]);
  let certificateSecretArn = existing.find((secret) => secret.Name === certificateSecretName)?.ARN;
  let privateKeySecretArn = existing.find((secret) => secret.Name === privateKeySecretName)?.ARN;

  if ((certificateSecretArn === undefined) !== (privateKeySecretArn === undefined)) {
    const missing = certificateSecretArn === undefined ? certificateSecretName : privateKeySecretName;
    const present = certificateSecretArn === undefined ? privateKeySecretName : certificateSecretName;
    throw new GeneralException(
      `${missing} is missing while ${present} exists, so the pair cannot be used and generating a new one would ` +
        `replace a certificate that may be in service. Restore ${missing}, or delete ${present} and re-run the deploy ` +
        'to generate a new pair.',
    );
  }

  let generated: { certificate: string; privateKey: string } | undefined;
  const tags = commonTags(request.tags);
  if (certificateSecretArn === undefined || privateKeySecretArn === undefined) {
    generated = generate(request, deps.openssl);
    certificateSecretArn = await deps.secrets.createSecret({
      Name: certificateSecretName,
      Description: `Self-Signed certificate for domain name: ${request.domainName}`,
      SecretString: generated.certificate,
      Tags: [...tags, { Key: SECRET_NAME_TAG, Value: certificateSecretName }],
      ...(request.kmsKeyId === undefined ? {} : { KmsKeyId: request.kmsKeyId }),
    });
    privateKeySecretArn = await deps.secrets.createSecret({
      Name: privateKeySecretName,
      Description: `Self-Signed certificate private key for domain name: ${request.domainName}`,
      SecretString: generated.privateKey,
      Tags: [...tags, { Key: SECRET_NAME_TAG, Value: privateKeySecretName }],
      ...(request.kmsKeyId === undefined ? {} : { KmsKeyId: request.kmsKeyId }),
    });
  }

  if (!request.importToAcm) return { certificateSecretArn, privateKeySecretArn };

  const issued = await deps.acm.listIssuedCertificates();
  let acmCertificateArn = issued.find((certificate) => certificate.DomainName === request.domainName)?.CertificateArn;
  if (acmCertificateArn === undefined) {
    if (generated === undefined) {
      throw new GeneralException(
        `no ISSUED ACM certificate for ${request.domainName}, and the secrets for ${request.certificateName} already ` +
          'exist, so there is nothing to import. Import the certificate held in ' +
          `${certificateSecretName} into ACM, or delete both secrets and re-run the deploy to generate a new pair.`,
      );
    }
    acmCertificateArn = await deps.acm.importCertificate({
      Certificate: generated.certificate,
      PrivateKey: generated.privateKey,
      Tags: tags,
    });
  }
  return { certificateSecretArn, privateKeySecretArn, acmCertificateArn };
}
