name: 'Ruff'
description: 'Runs Ruff Check and Ruff Format on the codebase'
runs:
  using: 'composite'
  steps:
    - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3
      with:
        args: "format --check --diff"
    - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3
